[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.install_systemd_service]
command = "sudo"
args = ["cp", "systemd/karo.bus.hub.service", "/etc/systemd/system/"]

[tasks.install_binary]
command = "sudo"
args = ["cp", "../target/release/karo-bus-hub", "/usr/bin/"]
dependencies = ["build"]

[tasks.install]
run_task = { name = ["install_systemd_service", "install_binary"] }
