[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.install_caro_service]
command = "sudo"
args = ["cp", "-f", "com.bus.monitor.service", "/etc/caro.services.d/"]

[tasks.install_binary]
command = "sudo"
args = ["cp", "../target/release/caro-bus-monitor", "/usr/bin/"]
dependencies = ["build"]

[tasks.install]
run_task = { name = ["install_caro_service", "install_binary"] }
